name: PR Build and Test

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  cleanup_previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: use node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

     # Cache every node_modules folder inside the monorepo
      - name: cache all node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}

      - name: npm install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build

      - name: Dirty Check
        run: npm run --silent dirtycheck
